3v-workspace/DataOcean

src/components/pages/datasets/DatasetsList.jsx

Hide the button "My Datasets"

---

src/components/pages/system/HomePage.jsx

Companies block changed for look like KVED block.
https://razom.atlassian.net/browse/DO-851?atlOrigin=eyJpIjoiZGQxOWIyNjJiNzBmNGFmZThhOWNlZGJiMDQxMTNmNDQiLCJwIjoiaiJ9

DO-851 Fix companies block on homepage 

---

public/docs/PrivacyPolicyEn.html
public/docs/PrivacyPolicyUk.html
src/components/pages/auth/SignUpForm.jsx

by the task request https://razom.atlassian.net/browse/DO-904, added  Privacy policy link to the Sign-Up page.
Corrected issue that only EN version opens.
Also added back function to "Back"  Privacy Policy, according to https://razom.atlassian.net/browse/DO-920 task. 
Finding out the necesserity of this task is in progress

DO-904 Added Privacy policy link

---

src/api.js
src/components/pages/system/HelpPage.jsx
src/components/pages/system/PepGraphPage.jsx
src/const/faqs.jsx

Corrected my task according to comments and corrected pepUrl

Added link to api documentation

---

src/components/pages/payment/SubscriptionsPage.jsx
src/locales/en/translation.json
src/locales/uk/translation.json

[DO-906] done

---

src/components/pages/system/HomePage.jsx

https://razom.atlassian.net/browse/DO-969
Transitive solution. If  it should be showed to visitors, but if it's not so necesserry - i'll close the request.

DO-969  TOP KVED platform homepage

---

src/components/pages/api/ApiPage.jsx
src/components/pages/payment/ProjectDetail.jsx

added token to API and project details pages

[DO-1091] Payments token

---

src/components/pages/system/ContactsPage.jsx
src/locales/en/translation.json
src/locales/uk/translation.json

Added law address and phone number to "Contacts" page.
https://razom.atlassian.net/browse/DO-1075

DO-1075  Update contacts (phone, address)

---

src/components/nav/TopBar.jsx

profile link deleted from menu
added 'my payments'

[do-1264] menu fix

---

src/components/pages/payment/ProjectDetail.jsx
src/components/pages/payment/SubscriptionsPage.jsx
src/locales/en/translation.json
src/locales/uk/translation.json

- Implemented back arrow to subscriptions page( if you came from project )

[DO-975] Back arrow

---

src/components/pages/payment/SubscriptionsPage.jsx

localizated subscription price

[do-1184] localization number

---

src/components/pages/datasets/company/CompanyUkList.jsx
src/components/pages/datasets/company/CompanyUkrList.jsx
src/components/pages/datasets/company/FopList.jsx
src/components/pages/datasets/koatuu/KoatuuList.jsx
src/components/pages/datasets/kved/KvedList.jsx
src/components/pages/datasets/pep/PepList.jsx
src/components/pages/datasets/street/StreetList.jsx
src/components/table/Table.jsx

added size to datasets and props for this size in table component

[DO-1332] DataSets table fix

---

src/components/nav/TopBarSearch.jsx
src/components/pages/datasets/DatasetsList.jsx

[do-1538] datasets searcher fix

---

src/components/pages/auth/SignUpForm.jsx
src/components/pages/profile/ChangeInfoBlock.jsx
src/locales/en/translation.json
src/locales/uk/translation.json
src/utils/yup.js

https://github.com/3v-workspace/Data_converter/pull/685

[DO - 1417] Add an optional "Phone" field to the registration form, as well as to the profile.

---

src/components/pages/datasets/sanctions/PersonSanctionList.jsx

[DO-1957] Add multiply citizenship countries

---

src/components/pages/datasets/pep/PepList.jsx
src/components/table/Table.jsx

All row space is clickable but text is selectable & copyable also

[DO-1641] Add pep row clickable

---

src/components/pages/system/HomePage.jsx
src/components/table/Pagination.jsx

For a more usable view of the general amount of number of records of all datasets divide hundreds, thousands, and millions by space.
E.g.
Exist now:  Показано від 1 до 10 із 5388170 записів
Must be: Показано від 1 до 10 із 5 388 170 записів

[DO-1230] Change view of number of records of all datasets

---

src/components/form-components/DateInput.jsx

N.B.: https://github.com/Hacker0x01/react-datepicker/issues/320

[DO-2313] Datepicker show wrong date in popup at page loading

---

src/components/table/Table.jsx

Кнопка для здійснення сортування має мати вигляд двох стрілочок розташованих вертикально в різних напрямках. По замовчуванню: ліва - вверх, права - вниз.
При першому відображенні сторінки обидва стрілочки не активні, мають сірий колір.
Сортування від А до Я буде здійснюватись при першому натисканні на цю кнопку. При цьому стрілочка з напряком сортування стає білого кольору, інша зникає. При другому натисканні - змінюється напрямок сортування і відповідно змінюється відображення стрілочек на протележне: перша зникає, а інша з'являється в білому кольорі.
При третьому натисканні - відбувається сортування по замовчуванню і з'являються обидві стрілочки в неактивному стані (сірого кольору).

[DO-2295][Bugfix] Realize new functional for sorting

---

src/utils/dateTime.jsx

[Bugfix] Date format

---

src/components/pages/datasets/kved/KvedList.jsx

Connected with https://github.com/3v-workspace/Data_converter/pull/1202

Add translation for NACE dataset

---

src/components/filter-fields/FilterField.jsx
src/components/pages/datasets/pep/PepDetail.jsx
src/components/pages/datasets/sanctions/PrintDownloadSanction.jsx
src/components/pages/payment/LogTable.jsx

[DO-2416] Add project API activity logging
